### ISSUE TITLE
Strange behavior with elixir-temp

### ISSUE THREAD

**Issue by lowks** [mgwidmann/elixir-pattern_tap#3]
I am using https://github.com/tuvistavie/elixir-temp in my code and I am trying to tap out a pattern but it does not seem to work:

Command:
```Temp.mkdir %{basedir: "/tmp"}```

Normal output of the command

```
iex(7)> Temp.mkdir %{basedir: "/tmp"}
{:ok, "/tmp/d-1478484066-19091-1t14635"}
```
Expected result: 

No errors encountered

Real result:
```
iex(7)> Temp.mkdir %{basedir: "/tmp"} |> tap({:ok, mystring}, mystring)  
** (CaseClauseError) no case clause matching: %{basedir: "/tmp"}
```

**Comment by lowks** [comment]
This: 
`iex(9)> Temp.mkdir(%{basedir: "/tmp"}) |> tap({:ok, mystring} ~> mystring)
"/tmp/d-1478484289-19091-1hbkmt1"`

seems to work though

**Comment by mgwidmann** [comment]
Huh, weird. `tap/2` (using the `~>`) just uses `tap/3`, so that is strange. Maybe its getting unquoted twice?

**Comment by lowks** [comment]
¯_(ツ)_/¯

**Comment by mgwidmann** [comment]
I'll have to see why it isn't matching when I get some time...

**Comment by mgwidmann** [comment]
I see your problem! You need the parens around the `Temp.mkdir` call. Its taking the `%{basedir: "/tmp"}` and sending that to `tap({:ok, mystring}, mystring)` which doesn't match. This is working as intended since you'd want to know when the pattern didnt fit what you expected.
